### ISSUE TITLE
Label as display: block

### ISSUE THREAD

**Issue by pabloalmunia** [graphery/stylent.css#2]
If `input` is defined as `display: block; width: 100%;`, the labels must defined equal.

**Comment by graphane** [comment]
Yes, the `label` must be displayed as `aling-block`, not as `block`, beause in some cases you can use `label` with a checkbox, but in other case you need a full width label. For this sencond case, please, use the auxliary class `.size-full-width`.

It's changed in version 0.0.4.

**Comment by pabloalmunia** [comment]
It's ok.  Thks.
